### ISSUE TITLE
[BUG/FIX] Closing the MDNS socket causes multiple autoconnects to fans to fail after the first device

### ISSUE THREAD

**Issue by JohnVidler** [jagribble/dyson-node#3]
**Describe the bug**
When `autoConnect()` finds a matching answer, it closes the MDNS socket globally, such that subsequent attempts to `autoConnect()` with new `DysonDevice` objects will fail.

**To Reproduce**
Have more than one device on the network and attempt to sequentially autoConnect to them all.

**Expected behaviour**
The devices after the first one should autoConnect as normal

**Package Version**
0.2.2

**Possible Fix 1 - leave the MDNS socket connected**
Simply remove the commented line below, and the socket remains viable for subsequent connections:

```javascript
async autoConnect() {
        return new Promise((resolve) => {
            const serialLocal = `${this.serial}.local`;
            const self = this;
            mdns.on('response', async (response) => {
                if (response.answers.length > 0) {
                    const answer = response.answers.find(a => a.name === serialLocal);
                    if (answer) {
                        // If correct answer then destroy the MDNS UDP socket
                        // mdns.destroy(); <-- Remove/Comment this line, then the socket remains after the first connection
                        self.deviceIP = answer.data;
                        await self.connectManually(this.serial, self.deviceIP);
                        resolve();
                    }
                }
            });
            mdns.query({
                questions: [{
                    name: `${this.serial}.local`,
                    type: 'A'
                }]
            })
        });
    }
```

Side effects: Socket remains open and receiving data beyond the initial connection phase, which is a little less than ideal, but probably harmless.

**Possible Fix 2 - Create on-demand MDNS resolvers**
Rather than having a single global MDNS resolver object, just create them on-demand when `autoConnect()` is invoked

```javascript
async autoConnect() {
        return new Promise((resolve) => {
            const serialLocal = `${this.serial}.local`;
            const self = this;
            const mdns = require('multicast-dns')({ loopback: true }); // Create a new MDNS resolver for each call
            mdns.on('response', async (response) => {
                if (response.answers.length > 0) {
                    const answer = response.answers.find(a => a.name === serialLocal);
                    if (answer) {
                        // If correct answer then destroy the MDNS UDP socket
                        mdns.destroy();
                        self.deviceIP = answer.data;
                        await self.connectManually(this.serial, self.deviceIP);
                        resolve();
                    }
                }
            });
            mdns.query({
                questions: [{
                    name: `${this.serial}.local`,
                    type: 'A'
                }]
            })
        });
    }
```

Side effects: Without some catch/timeout magic, if a device fails to connect, it will leave a hanging UDP socket waiting for a correct reply forever, which may cause problems if user logic attempts multiple autoConnect calls.

I've verified both ways above work, and I'm currently using Fix 1 for now as a workaround as it's a little more clean.

**Comment by jagribble** [comment]
Hey @JohnVidler sorry didn't see this issue until today. 

So from when I made the first version of this I found that leaving the mdns open caused some issues with performance (Although this was when I had good old fashioned console.logs in). 

I'm slightly leaning towards fix number 2 as it's designed to connect per device so an mdns per device seems like the right solution and also doesn't leave mdns sockets open. This also means that if you need to call autoConnect again for some reason (say it has disconnected and a user has pressed autoConnect) the mdns will be created and destroyed once it has connected again. But yes should have some form of catch timeout incase it doesn't connect. 

Happy for you to create a PR if you want? Have some other stuff on so don't have the time to fully test right now. Will have some free time Friday though if not.

**Comment by jagribble** [comment]
@JohnVidler I had a quick try at it and have tested for one fan. Could you try the PR (#4) for your multiple fans to see if it works as expected for you.

**Comment by JohnVidler** [comment]
@jagribble  Oh hey! I was going to build a PR for the second option, but I'll give yours a spin when I can - currently a bit swamped myself, but I'll probably have some time to have a try today or tomorrow, and will report back.

**Comment by JohnVidler** [comment]
Looks good, per review in [this PR](https://github.com/jagribble/dyson-node/pull/4#pullrequestreview-451000337) both fans connect successfully.

**Comment by jagribble** [comment]
Cool @JohnVidler will merge the PR and release a new version
